import Foundation
import AppKit
import XPareCore
import UniformTypeIdentifiers

/// What we read off the pasteboard before stripping: the best available
/// representation plus a hint about which one it was, so the controller can
/// decide whether to run HTML stripping on it.
public struct PasteboardSnapshot: Equatable {
    public enum Kind: Equatable {
        /// `public.html` markup. Should be fed through `strip_html`.
        case html
        /// RTF flattened to its plain-string attributed value.
        case rtf
        /// A plain string with no richer representation available.
        case plain
    }

    public let text: String
    public let kind: Kind

    public init(text: String, kind: Kind) {
        self.text = text
        self.kind = kind
    }
}

/// A pasteboard read that carries the generation it came from. The controller
/// uses this to avoid writing stale transform output over newer clipboard data.
public struct PasteboardRead: Equatable {
    public let snapshot: PasteboardSnapshot
    public let changeCount: Int

    public init(snapshot: PasteboardSnapshot, changeCount: Int) {
        self.snapshot = snapshot
        self.changeCount = changeCount
    }
}

/// The result of a size-aware pasteboard read. Carries no clipboard content
/// unless a bounded snapshot was accepted.
public enum PasteboardReadResult: Equatable {
    case content(PasteboardRead)
    case empty(changeCount: Int)
    case tooLarge(bytes: Int, changeCount: Int)
}

/// Bounded image representation read from the pasteboard for local OCR. The raw
/// bytes are clipboard-derived content, so callers must keep them local and
/// short-lived.
public struct PasteboardImage: Equatable, Sendable {
    public let data: Data
    public let pasteboardType: String

    public init(data: Data, pasteboardType: String) {
        self.data = data
        self.pasteboardType = pasteboardType
    }
}

/// An image pasteboard read that carries the generation it came from.
public struct PasteboardImageRead: Equatable, Sendable {
    public let image: PasteboardImage
    public let changeCount: Int

    public init(image: PasteboardImage, changeCount: Int) {
        self.image = image
        self.changeCount = changeCount
    }
}

/// The result of a size-aware image read. Carries no clipboard content unless a
/// bounded image representation was accepted.
public enum PasteboardImageReadResult: Equatable, Sendable {
    case content(PasteboardImageRead)
    case empty(changeCount: Int)
    case tooLarge(bytes: Int, changeCount: Int)
}

/// Abstraction over the system pasteboard so the controller is testable without
/// touching `NSPasteboard.general`. The real implementation is
/// ``SystemPasteboard``.
public protocol PasteboardProtocol: AnyObject {
    /// Monotonic change counter (mirrors `NSPasteboard.changeCount`).
    var changeCount: Int { get }

    /// True when the current contents declare one of the nspasteboard.org
    /// "do not process" marker types: `org.nspasteboard.ConcealedType`,
    /// `org.nspasteboard.TransientType`, or `org.nspasteboard.AutoGeneratedType`.
    /// Password managers and similar tools mark secrets/ephemeral buffers this
    /// way; automatic (continuous-mode) processing must leave them untouched.
    var hasDoNotProcessMarker: Bool { get }

    /// Read the best available representation, preferring rich formats so the
    /// core can coerce them to plain text. Reports `.empty` when there is no
    /// text-like content at all. Rich raw representations are size-checked
    /// before materializing/decoding them.
    func readBest(maxRepresentationBytes: Int) -> PasteboardReadResult

    /// Read a bounded image representation for local OCR. Reports `.empty`
    /// when no image-like representation is present. Raw image bytes are
    /// size-checked before Vision decodes or recognizes them.
    func readImage(maxRepresentationBytes: Int) -> PasteboardImageReadResult

    /// Replace the pasteboard contents **in place** with a single plain string:
    /// `clearContents()` then `setString(_:forType: .string)`. No other types
    /// are written, so the rich representation is dropped — which is the point.
    /// Returns the pasteboard generation after the write, or `nil` when the
    /// system rejected the string write. By that point `clearContents()` has
    /// already run, so on `nil` the caller must surface the failure — and must
    /// NOT record a self-write generation, because the clipboard now holds the
    /// cleared generation, not the transformed text.
    func writePlain(_ text: String) -> Int?

    /// Replace the pasteboard contents **in place** with a single file reference
    /// (`clearContents()` then the URL object), used by the opt-in paste-as-file
    /// feature so pasting attaches the file instead of dumping the raw string.
    /// No string type is written alongside — that would defeat the feature.
    /// Returns the pasteboard generation after the write, or `nil` when the
    /// system rejected the write (same post-`clearContents` caveat as
    /// ``writePlain(_:)``).
    func writeFileURL(_ url: URL) -> Int?
}

/// `NSPasteboard.general`-backed pasteboard.
public final class SystemPasteboard: PasteboardProtocol {
    private let pasteboard: NSPasteboard
    private static let preferredImageTypes: [NSPasteboard.PasteboardType] = [
        .png,
        NSPasteboard.PasteboardType("public.jpeg"),
        NSPasteboard.PasteboardType("public.heic"),
        NSPasteboard.PasteboardType("public.heif"),
        .tiff,
    ]
    private static let maxOversizedImageRepresentationSkips = 1

    public init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    /// The nspasteboard.org marker types that ask clipboard tools not to
    /// process the current contents (passwords, transient buffers,
    /// auto-generated data). See https://nspasteboard.org.
    private static let doNotProcessTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    public var changeCount: Int {
        pasteboard.changeCount
    }

    public var hasDoNotProcessMarker: Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains(where: Self.doNotProcessTypes.contains)
    }

    public func readBest(maxRepresentationBytes: Int) -> PasteboardReadResult {
        let generation = pasteboard.changeCount
        let ceiling = max(0, maxRepresentationBytes)

        // 1. Prefer HTML markup — hand it to the core's strip_html. Read the raw
        //    bytes first so an oversized rich representation is refused before
        //    Swift/AppKit materializes it as a String.
        if let htmlData = pasteboard.data(forType: .html),
            !htmlData.isEmpty
        {
            if htmlData.count > ceiling {
                return .tooLarge(bytes: htmlData.count, changeCount: generation)
            }
            if let html = Self.decodeHtml(htmlData),
                !html.isEmpty
            {
                return .content(
                    PasteboardRead(
                        snapshot: PasteboardSnapshot(text: html, kind: .html),
                        changeCount: generation))
            }
        }

        // 2. Otherwise RTF: flatten to its plain attributed-string value. We do
        //    the RTF->plain decode here (an OS/AppKit concern) rather than in
        //    the core, which only deals in plain/HTML/Markdown text.
        if let rtfData = pasteboard.data(forType: .rtf),
            !rtfData.isEmpty
        {
            if rtfData.count > ceiling {
                return .tooLarge(bytes: rtfData.count, changeCount: generation)
            }
            if let attributed = try? NSAttributedString(
                data: rtfData,
                options: [.documentType: NSAttributedString.DocumentType.rtf],
                documentAttributes: nil),
                !attributed.string.isEmpty
            {
                return .content(
                    PasteboardRead(
                        snapshot: PasteboardSnapshot(text: attributed.string, kind: .rtf),
                        changeCount: generation))
            }
        }

        // 3. Fall back to a plain string.
        if let plain = pasteboard.string(forType: .string),
            !plain.isEmpty
        {
            return .content(
                PasteboardRead(
                    snapshot: PasteboardSnapshot(text: plain, kind: .plain),
                    changeCount: generation))
        }

        return .empty(changeCount: generation)
    }

    public func readImage(maxRepresentationBytes: Int) -> PasteboardImageReadResult {
        let generation = pasteboard.changeCount
        let ceiling = max(0, maxRepresentationBytes)
        var largestOversizedRepresentation: Int?

        for type in imageTypesAvailableOnPasteboard() {
            guard let data = pasteboard.data(forType: type),
                !data.isEmpty
            else {
                continue
            }
            if data.count > ceiling {
                let largest = max(largestOversizedRepresentation ?? 0, data.count)
                guard largestOversizedRepresentation == nil,
                    Self.maxOversizedImageRepresentationSkips > 0
                else {
                    return .tooLarge(bytes: largest, changeCount: generation)
                }
                largestOversizedRepresentation = largest
                continue
            }
            return .content(
                PasteboardImageRead(
                    image: PasteboardImage(data: data, pasteboardType: type.rawValue),
                    changeCount: generation))
        }

        if let bytes = largestOversizedRepresentation {
            return .tooLarge(bytes: bytes, changeCount: generation)
        }
        return .empty(changeCount: generation)
    }

    public func writePlain(_ text: String) -> Int? {
        pasteboard.clearContents()
        // `setString` can fail (pasteboard-server error). The prior contents are
        // already gone by then and re-writing them could fail the same way, so
        // the failure is propagated for the caller to surface — never silently
        // treated as a successful self-write.
        guard pasteboard.setString(text, forType: .string) else { return nil }
        return pasteboard.changeCount
    }

    public func writeFileURL(_ url: URL) -> Int? {
        pasteboard.clearContents()
        guard pasteboard.writeObjects([url as NSURL]) else { return nil }
        return pasteboard.changeCount
    }

    private static func decodeHtml(_ data: Data) -> String? {
        // The final rung is a deliberate *lossy* UTF-8 decode (replacement chars) so we
        // always hand the core *some* markup rather than dropping the clipboard entirely
        // when every strict decode fails. That's exactly why the failable initializer that
        // `optional_data_string_conversion` prefers is wrong for that last rung.
        // swiftlint:disable optional_data_string_conversion
        String(data: data, encoding: .utf8)
            ?? String(data: data, encoding: .utf16)
            ?? String(data: data, encoding: .utf16LittleEndian)
            ?? String(data: data, encoding: .utf16BigEndian)
            ?? String(decoding: data, as: UTF8.self)
        // swiftlint:enable optional_data_string_conversion
    }

    private func imageTypesAvailableOnPasteboard() -> [NSPasteboard.PasteboardType] {
        guard let availableTypes = pasteboard.types else { return [] }
        var result: [NSPasteboard.PasteboardType] = []

        for type in Self.preferredImageTypes where availableTypes.contains(type) {
            result.append(type)
        }

        for type in availableTypes {
            guard !result.contains(type),
                Self.isImageType(type)
            else {
                continue
            }
            result.append(type)
        }

        return result
    }

    private static func isImageType(_ pasteboardType: NSPasteboard.PasteboardType) -> Bool {
        guard let type = UTType(pasteboardType.rawValue) else { return false }
        return type.conforms(to: .image)
    }
}
