/* SafetyStrip C ABI — the frozen, language-neutral boundary between the
   Rust core and native shells. Any change here is a compatibility event. */

#ifndef SAFETYSTRIP_FFI_H
#define SAFETYSTRIP_FFI_H

/* GENERATED by cbindgen — do not edit by hand. Run `cargo xtask gen-header`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Version of this C ABI. Bump on **any** change to the function signatures,
 * struct/enum layouts, or memory-ownership contract below. Adding a transform is
 * NOT an ABI change and must NOT bump this.
 *
 * History: v1 → v2 added [`SS_MAX_INPUT_BYTES`] and a new trailing status,
 * [`SsStatus::ErrInputTooLarge`]. Existing status values are unchanged, so a v1
 * caller still interprets `Ok`/`ErrNullArg`/`ErrInvalidConfig`/`ErrInternal`
 * correctly; only the new size ceiling is added.
 */
#define SS_ABI_VERSION 2

/**
 * Hard upper bound, in bytes, on the input [`ss_transform`] will accept. A larger
 * input returns [`SsStatus::ErrInputTooLarge`] *before* anything is read or
 * allocated, so a pathological size can never cause an out-of-memory abort or an
 * allocation-size overflow at the boundary.
 *
 * This is a **generous, platform-neutral backstop, not the everyday limit.** A
 * transform's peak working set is a few times its input, so the real ceiling is
 * memory-bound: the native shell enforces a tighter, RAM-proportional limit (it is
 * the only layer permitted to ask the OS how much memory exists) and refuses an
 * oversized clipboard gracefully. The headless CLI is intentionally uncapped, for
 * large file/log work where the caller manages its own memory.
 *
 * Written as a plain decimal literal (not `2 * 1024 * 1024 * 1024`) so the
 * cbindgen-generated `#define` is a single 64-bit-typed C constant: the expression
 * form would be evaluated in 32-bit `int` by a C compiler and overflow (2^31 >
 * INT_MAX), corrupting the value for C/C++ consumers and the Swift macro importer.
 */
#define SS_MAX_INPUT_BYTES 2147483648

/**
 * Result status for [`ss_transform`]. `repr(C)` so it is a plain C enum.
 */
typedef enum SsStatus {
  /**
   * Success. `*out` / `*out_len` describe a buffer the caller must free.
   */
  SS_STATUS_OK = 0,
  /**
   * A required pointer argument was null.
   */
  SS_STATUS_ERR_NULL_ARG = 1,
  /**
   * `config_json` was not valid UTF-8, not valid JSON, or an unsupported version.
   */
  SS_STATUS_ERR_INVALID_CONFIG = 2,
  /**
   * An unexpected internal error (e.g. a caught panic). Should never happen.
   */
  SS_STATUS_ERR_INTERNAL = 3,
  /**
   * `input_len` exceeded [`SS_MAX_INPUT_BYTES`]; nothing was read, allocated, or
   * transformed. (Added in ABI v2.)
   */
  SS_STATUS_ERR_INPUT_TOO_LARGE = 4,
} SsStatus;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the integer ABI version. See [`SS_ABI_VERSION`].
 */
uint32_t ss_abi_version(void);

/**
 * Returns a pointer to a static, NUL-terminated UTF-8 JSON string describing this
 * core's capabilities (name, version, config schema version, supported operations).
 *
 * The returned pointer is valid for the lifetime of the process and **must not be
 * freed**. Never returns null.
 */
const char *ss_capabilities_json(void);

/**
 * Transform `input` according to `config_json`.
 *
 * * `input` / `input_len` — UTF-8 text. Invalid UTF-8 is decoded losslessly
 *   (replacement characters) rather than rejected. `input` may be null only if
 *   `input_len` is 0.
 * * `config_json` — NUL-terminated UTF-8 JSON config. Must not be null.
 * * `out` / `out_len` — on `Ok`, `*out` receives a heap buffer of `*out_len` UTF-8
 *   bytes (not NUL-terminated) that the caller must release with [`ss_buffer_free`].
 *   On any error, `*out` is set to null and `*out_len` to 0. Both must not be null.
 *
 * Inputs larger than [`SS_MAX_INPUT_BYTES`] return [`SsStatus::ErrInputTooLarge`]
 * without reading `input` or allocating.
 *
 * # Safety
 * `input` must be valid for reads of `input_len` bytes (or null with `input_len`
 * 0); `config_json` must point to a valid NUL-terminated string; `out` and
 * `out_len` must be valid for writes.
 */
enum SsStatus ss_transform(const uint8_t *input,
                           size_t input_len,
                           const char *config_json,
                           uint8_t **out,
                           size_t *out_len);

/**
 * Free a buffer returned by [`ss_transform`], zeroizing it first so clipboard-derived
 * bytes do not linger in freed memory.
 *
 * `ptr`/`len` must be exactly the values produced by a single `ss_transform` call,
 * and must be freed at most once. A null `ptr` is a no-op.
 *
 * # Safety
 * `ptr` must originate from `ss_transform`'s `*out` with the matching `len`, not be
 * used afterwards, and not be freed more than once.
 */
void ss_buffer_free(uint8_t *ptr, size_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SAFETYSTRIP_FFI_H */
